export DYLD_LIBRARY_PATH="/opt/homebrew/opt/expat/lib:${DYLD_LIBRARY_PATH:-}"
export HF_HOME="/Users/danielwilches/.cache/huggingface"
export TRANSFORMERS_CACHE="/Users/danielwilches/.cache/huggingface/hub"
export SENTENCE_TRANSFORMERS_HOME="/Users/danielwilches/.cache/torch/sentence_transformers"
export RAG_EMBEDDING_MODEL_PATH="/Users/danielwilches/.cache/huggingface/hub/models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2/snapshots/e8f8c211226b894fcb81acc59f3b34ba3efd5f42"
export OLLAMA_BASE_URL="http://127.0.0.1:11434"
export OLLAMA_MODEL="qwen2.5:3b"
